volumes:
  pgdata: {}
  redis_data: {}

services:
  postgres:
    container_name: "tg_bot.postgres"
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ${HOME}/pgdata:/var/lib/postgresql/tg_bot
