"""fix manual

Revision ID: 21b36758e53c
Revises: 31de1d8bbc0d
Create Date: 2025-02-28 00:15:15.593880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21b36758e53c"
down_revision: Union[str, None] = "31de1d8bbc0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "users",
        "last_click_timestamp",
        existing_type=sa.TIMESTAMP(),
        server_default=sa.text("'2001-01-01 01:00:00'"),
    )
    op.alter_column(
        "users",
        "boost_timestamp",
        existing_type=sa.TIMESTAMP(),
        server_default=sa.text("'2001-01-01 01:00:00'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
