"""fix

Revision ID: 31de1d8bbc0d
Revises: fa6b8aa579f0
Create Date: 2025-02-28 00:14:02.161076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31de1d8bbc0d"
down_revision: Union[str, None] = "fa6b8aa579f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
