"""ondelete cascasde

Revision ID: 6169b8cf7719
Revises: bb4da93451cb
Create Date: 2025-02-09 01:26:21.711802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6169b8cf7719"
down_revision: Union[str, None] = "bb4da93451cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_task_user_id_fkey", "user_task", type_="foreignkey"
    )
    op.drop_constraint(
        "user_task_task_id_fkey", "user_task", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_task", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "user_task", "tasks", ["task_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_task", type_="foreignkey")
    op.drop_constraint(None, "user_task", type_="foreignkey")
    op.create_foreign_key(
        "user_task_task_id_fkey", "user_task", "tasks", ["task_id"], ["id"]
    )
    op.create_foreign_key(
        "user_task_user_id_fkey", "user_task", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
