"""boost renames

Revision ID: 8923f607e687
Revises: 7a1b340cfb58
Create Date: 2025-02-24 00:46:19.028793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8923f607e687"
down_revision: Union[str, None] = "7a1b340cfb58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("boost_timestamp", sa.TIMESTAMP(), nullable=True)
    )
    op.drop_column("users", "boost")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "boost", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "boost_timestamp")
    # ### end Alembic commands ###
