"""tasks description made nullabale true

Revision ID: bb4da93451cb
Revises: d15ae2e8e5ff
Create Date: 2025-02-01 07:57:22.618230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb4da93451cb"
down_revision: Union[str, None] = "d15ae2e8e5ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
