"""hueta

Revision ID: c6c0c28b71f7
Revises: 1ceb17881cca
Create Date: 2025-01-31 08:45:45.496149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6c0c28b71f7"
down_revision: Union[str, None] = "1ceb17881cca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "amount_of_referrals",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "amount_of_referrals")
    # ### end Alembic commands ###
