"""added last_click_timestamp

Revision ID: d3ee6c2d1cb4
Revises: a1749221f0d8
Create Date: 2025-02-23 23:10:54.773540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3ee6c2d1cb4"
down_revision: Union[str, None] = "a1749221f0d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("last_click_timestamp", sa.TIMESTAMP(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_click_timestamp")
    # ### end Alembic commands ###
