from .farm_stars import *
from .get_link import *
from .main import *
from .start import *
from .reviews import *
from .faq import *
from .boost import *
from .profile import *
from .mini_games import *
from .tasks import *
from .rating import *
